packages:
  - packages/*

catalog:
  typescript: ^5.8.3

ignoredBuiltDependencies:
  - '@bolinjs/vite-plugin-log-label'
  - '@nestjs/core'
  - '@swc/core'
  - core-js
  - esbuild
  - node-pty
  - simple-git-hooks
  - vue-demi

onlyBuiltDependencies:
  - electron
